global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # Spike Compiler application metrics
  - job_name: 'spike-compiler'
    static_configs:
      - targets: ['spike-compiler:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Python application metrics
  - job_name: 'python-app'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093